### ISSUE TITLE
Failed to request both edges events for lines: 13, 6

### ISSUE THREAD

**Issue by OlivierShi** [NishimiyaShoukou/DOLYDV#2]
Hey, thanks for sharing this project.
When i built and ran it, the move_robot_task failed, and all other tasks worked well. The failure info is `Failed to request both edges events for lines: 13, 6`, any idea for this?

**Comment by NishimiyaShoukou** [comment]
Hi there,

The error message you encountered is related to testing the motor encoder data for the DOLY robot. The failure occurs because the interrupt pins are already occupied by the official kernel module `doly_drive`. To resolve this issue, you can temporarily unload this module by entering the command `rmmod doly_drive` in the command line, or add system("rmmod doly_drive") to the hardware initialization part of your program. Alternatively, you can comment out the encoder-related functions in the `move_task` function, specifically `EtrLeft.startEncoder(13,6);`.

It is worth noting that the current method of reading the encoder is only suitable for testing the encoder. In actual multi-task operations, it may cause the `move_task` thread to block, and this needs further improvement.

**Comment by OlivierShi** [comment]
Tried `rmmod doly_drive` and it worked. Really appreciate your quick reply.
